name:  contextualSearch
author:  thinkphp
current: v2.0
category: Request
tags:  [search,widget,form,request,yql,boss,interface,contextual,jsonp]
docs:  http://github.com/thinkphp/contextualSearch/blob/master/Docs/contextualSearch.md
demo:  http://thinkphp.github.com/contextualSearch/
