name:  contextualSearch
author:  thinkphp
current: 1.0
category: Request
tags:  [search,widget,form,request,yql,boss,interface,contextual,jsonp]
docs:  http://github.com/thinkphp/contextualSearch/blob/master/Docs/contextualSearch.md
demo:  http://thinkphp.ro/apps/js-hacks/contextualSearch/contextual-search-moo.html
